version: 0.2
env:
  variables:
    TAG-DOCKER: $CODEBUILD_BUILD_NUMBER
phases:
  pre-build:
    commands:
      - echo test
  # pre-build:
  #    commands:
  #     - author Minhnx
  #     - echo ===============  start pre-build  ======================
  #     - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129848715.dkr.ecr.us-east-1.amazonaws.com
  #     - echo ====================== end pre-build ======================
  # build:
  #   commands:
  #     - echo ====================== start build ======================
  #     - docker build -t $TAG-DOCKER --file ./analytics/Dockerfile .
  #     - echo ====================== end build ======================
  # post-build:
  #   commands:
  #     - echo ====================== start post build ======================
  #     - docker push $TAG-DOCKER
  #     - echo ====================== end post build ======================

