version: 0.2
phases:
  pre_build:
     commands:
      - echo author Minhnx
      - echo ===============  start pre-build  ======================
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129848715.dkr.ecr.us-east-1.amazonaws.com
      - echo ====================== end pre-build ======================
  build:
    commands:
      - echo ====================== start build ======================
      - echo tag $CODEBUILD_BUILD_NUMBER
      - docker build -t project-3:$CODEBUILD_BUILD_NUMBER --file ./analytics/Dockerfile .
      - docker images
      - docker tag $CODEBUILD_BUILD_NUMBER 376129848715.dkr.ecr.us-east-1.amazonaws.com/project-3:$CODEBUILD_BUILD_NUMBER
      - echo ====================== end build ======================
  post_build:
    commands:
      - echo ====================== start post build ======================

      - docker push 376129848715.dkr.ecr.us-east-1.amazonaws.com/project-3:$CODEBUILD_BUILD_NUMBER
      - echo ====================== end post build ======================
