version: 0.2
env:
  variables:
    TAG_DOCKER: $CODEBUILD_BUILD_NUMBER
phases:
  pre_build:
     commands:
      - echo author Minhnx
      - echo ===============  start pre-build  ======================
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129848715.dkr.ecr.us-east-1.amazonaws.com
      - echo ====================== end pre-build ======================
  build:
    commands:
      - echo ====================== start build ======================
      - echo tag $TAG_DOCKER
      - docker build -t $TAG_DOCKER --file ./analytics/Dockerfile .
      - echo ====================== end build ======================
  post_build:
    commands:
      - echo ====================== start post build ======================
      - docker push $TAG_DOCKER
      - echo ====================== end post build ======================
