apiVersion: v1
kind: ConfigMap
metadata:
  name: ConfigMap
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: Secret
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==