apiVersion: v1
kind: Service
metadata:
  name: project-3
spec:
  type: LoadBalancer
  selector:
    service: project-3
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-3
  labels:
    name: project-3
spec:
  replicas: 1
  selector:
    matchLabels:
      service: project-3
  template:
    metadata:
      labels:
        service: project-3
    spec:
      containers:
      - name: project-31
        image: 376129848715.dkr.ecr.us-east-1.amazonaws.com/project-3:24
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: configmap
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: Secret_Project3
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ConfigMap_Project3
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: ConfigMap_Project3
              key: POSTGRES_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ConfigMap_Project3
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ConfigMap_Project3
              key: DB_PORT
      restartPolicy: Always