apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-project3
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-project3
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==