apiVersion: v1
kind: Service
metadata:
  name: coworking1
spec:
  type: LoadBalancer
  selector:
    service: coworking1
  ports:
  - name: "5154"
    protocol: TCP
    port: 5154
    targetPort: 5154
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking1
  labels:
    name: coworking1
spec:
  replicas: 2
  selector:
    matchLabels:
      service: coworking1
  template:
    metadata:
      labels:
        service: coworking1
    spec:
      containers:
      - name: coworking1
        image: 376129848715.dkr.ecr.us-east-1.amazonaws.com/project-3:24
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5154
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5154
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: configmap-project3
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-project3
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap-project3
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-project3
              key: POSTGRES_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-project3
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-project3
              key: DB_PORT
      restartPolicy: Always